import 'package:normaldo_gaming/core/errors.dart';
import 'package:normaldo_gaming/domain/knowledge/item_description.dart';
import 'package:normaldo_gaming/domain/pull_up_game/items.dart';

abstract interface class KnowledgeRepository {
  List<ItemDescription> get itemDescriptions;
  ItemDescription descriptionOf(Items item);
}

final class KnowledgeRepositoryImpl implements KnowledgeRepository {
  @override
  ItemDescription descriptionOf(Items item) {
    return itemDescriptions.firstWhere(
      (element) => element.item == item && item != Items.hugeItem,
      orElse: () => throw UnexpectedError(),
    );
  }

  @override
  List<ItemDescription> get itemDescriptions => [
        ItemDescription(
          item: Items.trashBin,
          description: _descKey(Items.trashBin),
          isGood: false,
          damage: 1,
          skills: [],
          gives: [],
          locations: ['sewers', 'frontyard', 'backyard', 'park', 'beach'],
        ),
        ItemDescription(
            item: Items.pizza,
            description: _descKey(Items.pizza),
            isGood: true,
            damage: 0,
            skills: [],
            gives: ['1 pizza'],
            locations: ['everywhere']),
        ItemDescription(
            item: Items.dollar,
            description: _descKey(Items.dollar),
            isGood: true,
            damage: 0,
            skills: [],
            gives: ['1 \$'],
            locations: ['everywhere']),
        ItemDescription(
          item: Items.fatPizza,
          description: _descKey(Items.fatPizza),
          isGood: true,
          damage: 0,
          locations: ['everywhere'],
          skills: ['get opened and drop a bunch of pizza'],
          gives: ['10-20 pizza'],
        ),
        ItemDescription(
          item: Items.homeless,
          description: _descKey(Items.homeless),
          isGood: false,
          damage: 1,
          locations: ['sewers', 'parking', 'backyard', 'park'],
          skills: ['throw himself forward'],
          gives: [],
        ),
        ItemDescription(
            item: Items.moneyBag,
            description: _descKey(Items.moneyBag),
            isGood: true,
            damage: 0,
            locations: ['everywhere'],
            skills: [],
            gives: ['10 \$']),
        ItemDescription(
          item: Items.boombox,
          description: _descKey(Items.boombox),
          isGood: true,
          damage: 0,
          locations: ['everywhere'],
          skills: ['explodes everything'],
          gives: [],
        ),
        ItemDescription(
            item: Items.cocktail,
            description: _descKey(Items.cocktail),
            isGood: false,
            damage: 0,
            locations: ['beach', 'jacuzzi', 'island', 'limo'],
            skills: ['slows you down'],
            gives: []),
        ItemDescription(
            item: Items.molotov,
            description: _descKey(Items.molotov),
            isGood: false,
            damage: 1,
            locations: ['everywhere'],
            skills: ['changes line'],
            gives: []),
        ItemDescription(
            item: Items.hourglass,
            description: _descKey(Items.hourglass),
            isGood: true,
            damage: 0,
            locations: ['everywhere'],
            skills: ['slows time'],
            gives: []),
        ItemDescription(
            item: Items.punch,
            description: _descKey(Items.punch),
            isGood: false,
            damage: 0,
            locations: ['backyard'],
            skills: ['flies through the line'],
            gives: []),
        ItemDescription(
            item: Items.allIn,
            description: _descKey(Items.allIn),
            isGood: false,
            damage: 0,
            locations: ['casino', 'jacuzzi'],
            skills: ['takes 10-50 \$'],
            gives: []),
        ItemDescription(
          item: Items.angryDog,
          description: _descKey(Items.angryDog),
          isGood: false,
          damage: 0,
          locations: ['everywhere'],
          skills: ['barks then cleans the line'],
          gives: [],
        ),
        ItemDescription(
            item: Items.bananaPeel,
            description: _descKey(Items.bananaPeel),
            isGood: false,
            damage: 0,
            locations: ['sewers', 'beach', 'backyard'],
            skills: ['slows you down'],
            gives: []),
        ItemDescription(
            item: Items.beer,
            description: _descKey(Items.beer),
            isGood: false,
            damage: 0,
            locations: ['beach', 'club', 'backyard', 'park'],
            skills: ['slows you down'],
            gives: []),
        ItemDescription(
            item: Items.cannibal,
            description: _descKey(Items.cannibal),
            isGood: false,
            damage: 0,
            locations: ['island'],
            skills: ['throw himself forward'],
            gives: []),
        ItemDescription(
            item: Items.casinoChip,
            description: _descKey(Items.casinoChip),
            isGood: false,
            damage: 0,
            locations: ['casino', 'jacuzzi'],
            skills: ['takes 1 \$'],
            gives: []),
        ItemDescription(
            item: Items.greenPoison,
            description: _descKey(Items.greenPoison),
            isGood: false,
            damage: 0,
            locations: ['club', 'island'],
            skills: ['slows you down'],
            gives: []),
        ItemDescription(
            item: Items.compass,
            description: _descKey(Items.compass),
            isGood: false,
            damage: 0,
            locations: ['beach', 'yacht', 'ship wreck'],
            skills: ['inverts control'],
            gives: []),
        ItemDescription(
            item: Items.energizer,
            description: _descKey(Items.energizer),
            isGood: true,
            damage: 0,
            locations: ['everywhere'],
            skills: ['speed you up'],
            gives: []),
        ItemDescription(
            item: Items.bird,
            description: _descKey(Items.bird),
            isGood: false,
            damage: 1,
            locations: ['everywhere'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.snake,
            description: _descKey(Items.snake),
            isGood: false,
            damage: 1,
            locations: ['island'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.policeAlarm,
            description: _descKey(Items.policeAlarm),
            isGood: false,
            damage: 1,
            locations: ['limo', 'bank'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.gun,
            description: _descKey(Items.gun),
            isGood: false,
            damage: 1,
            locations: ['bank'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.bubbles,
            description: _descKey(Items.bubbles),
            isGood: false,
            damage: 1,
            locations: ['jacuzzi'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.girl,
            description: _descKey(Items.girl),
            isGood: false,
            damage: 0,
            locations: ['club', 'limo'],
            skills: ['slows you down'],
            gives: []),
        ItemDescription(
            item: Items.goldClocks,
            description: _descKey(Items.goldClocks),
            isGood: false,
            damage: 0,
            locations: ['casino', 'bank'],
            skills: ['slows time'],
            gives: []),
        ItemDescription(
            item: Items.handcuffs,
            description: _descKey(Items.handcuffs),
            isGood: false,
            damage: 0,
            locations: ['parking', 'bank'],
            skills: ['ends game'],
            gives: []),
        ItemDescription(
            item: Items.caseyMask,
            description: _descKey(Items.caseyMask),
            isGood: true,
            damage: 0,
            locations: ['everywhere'],
            skills: ['damage immune'],
            gives: []),
        ItemDescription(
            item: Items.loserTicket,
            description: _descKey(Items.loserTicket),
            isGood: false,
            damage: 0,
            locations: ['club', 'casino', 'limo', 'yacht', 'jacuzzi'],
            skills: ['takes all of your money'],
            gives: []),
        ItemDescription(
            item: Items.magicHat,
            description: _descKey(Items.magicHat),
            isGood: true,
            damage: 0,
            locations: ['everywhere'],
            skills: ['slow immune'],
            gives: []),
        ItemDescription(
            item: Items.magicBox,
            description: _descKey(Items.magicBox),
            isGood: true,
            damage: 0,
            locations: ['everywhere'],
            skills: ['get opened and drop a bunch of items'],
            gives: []),
        ItemDescription(
            item: Items.magnet,
            description: _descKey(Items.magnet),
            isGood: true,
            damage: 0,
            locations: ['everywhere'],
            skills: ['instantly pulls pizza and \$'],
            gives: []),
        ItemDescription(
            item: Items.note,
            description: _descKey(Items.note),
            isGood: false,
            damage: 1,
            locations: ['club'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.note2,
            description: _descKey(Items.note2),
            isGood: false,
            damage: 2,
            locations: ['club'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.phone,
            description: _descKey(Items.phone),
            isGood: false,
            damage: 0,
            locations: ['limo', 'yacht'],
            skills: ['slows you down'],
            gives: []),
        ItemDescription(
            item: Items.spadesCard,
            description: _descKey(Items.spadesCard),
            isGood: false,
            damage: 1,
            locations: ['casino'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.policeman,
            description: _descKey(Items.policeman),
            isGood: false,
            damage: 1,
            locations: ['parking', 'backyard', 'limo', 'bank', 'park'],
            skills: ['calls help'],
            gives: []),
        ItemDescription(
            item: Items.security,
            description: _descKey(Items.security),
            isGood: false,
            damage: 1,
            locations: ['club', 'bank'],
            skills: ['calls help'],
            gives: []),
        ItemDescription(
            item: Items.shipPart,
            description: _descKey(Items.shipPart),
            isGood: false,
            damage: 1,
            locations: ['river', 'yacht', 'ship wreck'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.cone,
            description: _descKey(Items.cone),
            isGood: false,
            damage: 1,
            locations: ['sewers', 'river', 'parking'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.stone,
            description: _descKey(Items.stone),
            isGood: false,
            damage: 1,
            locations: ['beach'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.letterBottle,
            description: _descKey(Items.letterBottle),
            isGood: false,
            damage: 0,
            locations: ['river', 'yacht', 'ship wreck'],
            skills: ['slows you down'],
            gives: []),
        ItemDescription(
            item: Items.roadSign,
            description: _descKey(Items.roadSign),
            isGood: false,
            damage: 1,
            locations: ['sewers'],
            skills: [],
            gives: []),
        ItemDescription(
            item: Items.umbrella,
            description: _descKey(Items.umbrella),
            isGood: false,
            damage: 1,
            locations: ['river', 'beach'],
            skills: [],
            gives: []),
      ];

  String _descKey(Items item) => '${item.name}Desc';
}
