import 'package:normaldo_gaming/core/errors.dart';
import 'package:normaldo_gaming/domain/knowledge/item_description.dart';
import 'package:normaldo_gaming/domain/pull_up_game/items.dart';

abstract interface class KnowledgeRepository {
  List<ItemDescription> get itemDescriptions;
  ItemDescription descriptionOf(Items item);
}

final class KnowledgeRepositoryImpl implements KnowledgeRepository {
  @override
  ItemDescription descriptionOf(Items item) {
    return itemDescriptions.firstWhere(
      (element) => element.item != item && item != Items.hugeItem,
      orElse: () => throw UnexpectedError(),
    );
  }

  @override
  List<ItemDescription> get itemDescriptions => Items.values
      .where((e) =>
          e != Items.hugeItem &&
          e != Items.shredder &&
          e != Items.shredderSword)
      .map((item) => switch (item) {
            Items.trashBin => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                skills: [],
                gives: [],
                locations: ['sewers', 'yards', 'backyard', 'park', 'beach'],
              ),
            Items.pizza => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                skills: [],
                gives: ['1 pizza'],
                locations: ['everywhere']),
            Items.dollar => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                skills: [],
                gives: ['1 ndollar'],
                locations: ['everywhere']),
            Items.fatPizza => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['get opened and drop a bunch of pizza'],
                gives: ['10-20 pizza'],
              ),
            Items.homeless => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['sewers', 'parking', 'backyard', 'park'],
                skills: ['throw himself forward'],
                gives: [],
              ),
            Items.moneyBag => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: [],
                gives: ['10 ndollars']),
            Items.boombox => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['explodes everything'],
                gives: [],
              ),
            Items.cocktail => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['beach', 'jacuzzi', 'island', 'limo'],
                skills: ['slows you down'],
                gives: []),
            Items.molotov => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['everywhere'],
                skills: ['changes line'],
                gives: []),
            Items.hourglass => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['slows time'],
                gives: []),
            Items.punch => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['backyard'],
                skills: ['cleans a line'],
                gives: []),
            Items.allIn => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['casino', 'jacuzzi'],
                skills: ['takes 10-50 ndollars'],
                gives: []),
            Items.angryDog => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['everywhere'],
                skills: ['barks then cleans the line'],
                gives: ['yards', 'park']),
            Items.bananaPeel => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['sewers', 'beach', 'backyard'],
                skills: ['slows you down'],
                gives: []),
            Items.beer => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['beach', 'club', 'backyard', 'park'],
                skills: ['slows you down'],
                gives: []),
            Items.cannibal => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['island'],
                skills: ['throw himself forward'],
                gives: []),
            Items.casinoChip => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['casino', 'jacuzzi'],
                skills: ['takes 1 ndollar'],
                gives: []),
            Items.greenPoison => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['club', 'island'],
                skills: ['slows you down'],
                gives: []),
            Items.compass => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['beach', 'yacht', 'ship wreck'],
                skills: ['inverts control'],
                gives: []),
            Items.energizer => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['speed you up'],
                gives: []),
            Items.bird => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['everywhere'],
                skills: [],
                gives: []),
            Items.snake => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['island'],
                skills: [],
                gives: []),
            Items.policeAlarm => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['limo', 'bank'],
                skills: [],
                gives: []),
            Items.gun => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['bank'],
                skills: [],
                gives: []),
            Items.bubbles => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['jacuzzi'],
                skills: [],
                gives: []),
            Items.girl => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['club', 'limo'],
                skills: ['slows you down'],
                gives: []),
            Items.goldClocks => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['casino', 'bank'],
                skills: ['slows time'],
                gives: []),
            Items.handcuffs => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['parking', 'bank'],
                skills: ['ends game'],
                gives: []),
            Items.caseyMask => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['damage immune'],
                gives: []),
            Items.loserTicket => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['club', 'casino', 'limo', 'yacht', 'jacuzzi'],
                skills: ['takes all your money'],
                gives: []),
            Items.magicHat => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['immune to slowing'],
                gives: []),
            Items.magicBox => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['get opened and drop a bunch of items'],
                gives: []),
            Items.magnet => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: true,
                damage: 0,
                locations: ['everywhere'],
                skills: ['instantly pulls pizza and ndollars'],
                gives: []),
            Items.note => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['club'],
                skills: [],
                gives: []),
            Items.note2 => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 2,
                locations: ['club'],
                skills: [],
                gives: []),
            Items.phone => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['limo', 'yacht'],
                skills: ['slows you down'],
                gives: []),
            Items.spadesCard => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['casino'],
                skills: [],
                gives: []),
            Items.policeman => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['parking', 'backyard', 'limo', 'bank', 'park'],
                skills: ['calls help'],
                gives: []),
            Items.security => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['club', 'bank'],
                skills: ['calls help'],
                gives: []),
            Items.shipPart => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['river', 'yacht', 'ship wreck'],
                skills: [],
                gives: []),
            Items.cone => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['sewers', 'river', 'parking'],
                skills: [],
                gives: []),
            Items.stone => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['beach'],
                skills: [],
                gives: []),
            Items.letterBottle => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['river', 'yacht', 'ship wreck'],
                skills: ['slows you down'],
                gives: []),
            Items.roadSign => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['sewers'],
                skills: [],
                gives: []),
            Items.umbrella => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 1,
                locations: ['river', 'beach', 'beach', ''],
                skills: [],
                gives: []),
            // BOSSES&ATTACKS
            Items.shredder => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['everywhere'],
                skills: [],
                gives: ['15 ndollars']),
            Items.shuriken => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['everywhere'],
                skills: [],
                gives: ['15 ndollars']),
            Items.shredderSword => ItemDescription(
                item: item,
                description: _descKey(item),
                isGood: false,
                damage: 0,
                locations: ['everywhere'],
                skills: [],
                gives: ['15 ndollars']),
            _ => throw UnexpectedError(),
          })
      .toList();

  // String _descKey(Items item) => '${item.name}Desc';
  String _descKey(Items item) => 'Long time agoo this item...';
}
