name: normaldo_gaming
description: A new Flutter project.
publish_to: 'none'
version: 0.13.0+18

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  flame: ^1.8.0
  flame_bloc: ^1.9.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  equatable: ^2.0.5

  # Ads
  unity_ads_plugin: ^0.3.8

  # Database
  hive: ^2.2.3

  # Splash&Icon
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

  # Audio
  flame_audio: ^2.1.4

  # Routing
  go_router: ^10.1.2

  # DI
  flutter_simple_dependency_injection: ^2.0.0

  # Network
  chopper: ^7.0.9

  # Storage
  flutter_secure_storage: ^9.0.0

  # Others
  home_indicator: ^2.0.2
  flutter_vibrate: ^1.3.0
  phone_state: ^1.0.3

  # Localization
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.7.1
  chopper_generator: ^7.0.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  background_image: assets/images/splash.png
  # branding: assets/branding-development.png
  # color_dark: "#121212"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png

  android_12:
    background_image: assets/images/splash.png
    # image_dark: assets/logo-development.png
    # icon_background_color_dark: "#121212"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/slot_machine.png
    - assets/images/2.0x/slot_machine.png
    - assets/images/3.0x/slot_machine.png
    - assets/images/backgrounds/
    - assets/images/backgrounds/2.0x/
    - assets/images/backgrounds/3.0x/
    - assets/images/backgrounds/bg0/
    - assets/images/normaldo/
    - assets/images/normaldo/2.0x/
    - assets/images/normaldo/3.0x/
    - assets/images/stickers/
    - assets/images/stickers/2.0x/
    - assets/images/stickers/3.0x/

    - assets/audio/
    - assets/audio/sfx/

  fonts:
    # - family: HyperStiffRoundBootiedOpossumRegular
    #   fonts:
    #     - asset: fonts/HyperStiffRoundBootiedOpossumRegular.ttf

    - family: NormaldoFont
      fonts:
        - asset: fonts/NormaldoFont.ttf
