name: normaldo_gaming
description: A new Flutter project.
publish_to: 'none'
version: 0.16.3+28

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  flame: ^1.8.0
  flame_bloc: ^1.9.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  equatable: ^2.0.5

  # UI
  expandable: ^5.0.1
  scrollable_positioned_list: ^0.3.8
  animated_text_kit: ^4.2.2

  # Ads
  unity_ads_plugin: ^0.3.14

  # Database
  hive: ^2.2.3

  # Splash&Icon
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

  # Media
  flame_audio: ^2.1.4
  video_player: ^2.8.2

  # Routing
  go_router: ^12.1.1

  # DI
  flutter_simple_dependency_injection: ^2.0.0

  # Network
  chopper: ^7.0.9

  # Storage
  flutter_secure_storage: ^9.0.0

  # Others
  # home_indicator: ^2.0.2
  flutter_vibrate: ^1.3.0
  phone_state: ^1.0.3
  ntp: ^2.0.0
  # app_version_update: ^4.0.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6

  # Localization
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.7.1
  chopper_generator: ^7.0.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  background_image: assets/images/splash.png
  # branding: assets/branding-development.png
  # color_dark: "#121212"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png

  android_12:
    background_image: assets/images/splash.png
    # image_dark: assets/logo-development.png
    # icon_background_color_dark: "#121212"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/video/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/slot_machine.png
    - assets/images/2.0x/slot_machine.png
    - assets/images/3.0x/slot_machine.png
    - assets/images/backgrounds/
    - assets/images/backgrounds/2.0x/
    - assets/images/backgrounds/3.0x/
    - assets/images/backgrounds/bg0/
    - assets/images/normaldo/
    - assets/images/normaldo/2.0x/
    - assets/images/normaldo/3.0x/
    - assets/images/normaldo/batman/
    - assets/images/normaldo/batman/2.0x/
    - assets/images/normaldo/batman/3.0x/
    - assets/images/normaldo/dracula/
    - assets/images/normaldo/dracula/2.0x/
    - assets/images/normaldo/dracula/3.0x/
    - assets/images/normaldo/glasses/
    - assets/images/normaldo/glasses/2.0x/
    - assets/images/normaldo/glasses/3.0x/
    - assets/images/normaldo/halloween/
    - assets/images/normaldo/halloween/2.0x/
    - assets/images/normaldo/halloween/3.0x/
    - assets/images/normaldo/harry_potter/
    - assets/images/normaldo/harry_potter/2.0x/
    - assets/images/normaldo/harry_potter/3.0x/
    - assets/images/normaldo/new_year/
    - assets/images/normaldo/new_year/2.0x/
    - assets/images/normaldo/new_year/3.0x/
    - assets/images/normaldo/pirate/
    - assets/images/normaldo/pirate/2.0x/
    - assets/images/normaldo/pirate/3.0x/
    - assets/images/normaldo/spider_man/
    - assets/images/normaldo/spider_man/2.0x/
    - assets/images/normaldo/spider_man/3.0x/
    - assets/images/normaldo/viking/
    - assets/images/normaldo/viking/2.0x/
    - assets/images/normaldo/viking/3.0x/
    - assets/images/normaldo/wizard/
    - assets/images/normaldo/wizard/2.0x/
    - assets/images/normaldo/wizard/3.0x/
    - assets/images/stickers/
    - assets/images/stickers/2.0x/
    - assets/images/stickers/3.0x/
    - assets/images/main_screen/
    - assets/images/main_screen/2.0x/
    - assets/images/main_screen/3.0x/
    - assets/images/ui/the_path/
    - assets/images/ui/the_path/2.0x/
    - assets/images/ui/the_path/3.0x/
    - assets/images/ui/auth/
    - assets/images/ui/auth/2.0x/
    - assets/images/ui/auth/3.0x/
    - assets/images/bosses/
    - assets/images/bosses/2.0x/
    - assets/images/bosses/3.0x/
    - assets/images/us/

    - assets/audio/
    - assets/audio/sfx/
    - assets/audio/sfx/ui/
    - assets/audio/skins/batman/
    - assets/audio/skins/glasses/
    - assets/audio/skins/halloween/
    - assets/audio/skins/pirate/
    - assets/audio/skins/harry_potter/
    - assets/audio/skins/new_year/
    - assets/audio/skins/spider_man/
    - assets/audio/skins/dracula/
    - assets/audio/skins/viking/
    - assets/audio/skins/wizard/

  fonts:
    # - family: HyperStiffRoundBootiedOpossumRegular
    #   fonts:
    #     - asset: fonts/HyperStiffRoundBootiedOpossumRegular.ttf

    - family: NormaldoFont
      fonts:
        - asset: fonts/NormaldoFont.ttf
